export const BLOG_POSTS = [
  {
    slug: 'nutricion-perro-energia',
    title: 'Alimentación correcta: cómo darle energía a tu perro',
    excerpt: 'Guía práctica para elegir el alimento según edad, tamaño y nivel de actividad.',
    image: '/food.png',
    imageAlt: 'Alimento premium para perros',
    category: 'Nutrición',
    date: '8 min lectura',
    author: 'Dr. Martínez',
  },
  {
    slug: 'salud-gato-prevencion',
    title: 'Prevención en gatos: 5 señales de que algo anda mal',
    excerpt: 'Cambios de comportamiento que todo dueño debe conocer antes de que sea tarde.',
    image: '/food2.png',
    imageAlt: 'Gato descansando en una cama',
    category: 'Salud',
    date: '6 min lectura',
    author: 'Dra. Sánchez',
  },
  {
    slug: 'entrenamiento-basico-perro',
    title: 'Entrenamiento básico: comandos que todo perro debe saber',
    excerpt: 'Métodos positivos para enseñar sentado, ven aquí y no saltes en 2 semanas.',
    image: '/food3.png',
    imageAlt: 'Perro obediente sentado',
    category: 'Entrenamiento',
    date: '10 min lectura',
    author: 'Prof. López',
  },
  {
    slug: 'cuidado-perro-hot',
    title: 'Cuidados estacionales: protege a tu perro del calor',
    excerpt: 'Hidratación, sombra y horarios de paseo para que tu perro esté seguro en verano.',
    image: '/categoria.png',
    imageAlt: 'Perro fresco bajo sombra',
    category: 'Salud',
    date: '5 min lectura',
    author: 'Dr. Martínez',
  },
  {
    slug: 'nutricion-gato-humedo',
    title: '¿Alimento húmedo o seco? Lo que tu gato realmente necesita',
    excerpt: 'Comparación honesta entre ambas opciones y cuándo combinarlas.',
    image: '/categories.png',
    imageAlt: 'Plato de alimento para gato',
    category: 'Nutrición',
    date: '7 min lectura',
    author: 'Dra. Sánchez',
  },
  {
    slug: 'entrenamiento-gato-arena',
    title: 'Cómo enseñar a tu gato a usar la arena correctamente',
    excerpt: 'Trucos de refuerzo positivo para evitar sorpresas fuera de la caja.',
    image: '/detectives.png',
    imageAlt: 'Gato usando arena sanitaria',
    category: 'Entrenamiento',
    date: '4 min lectura',
    author: 'Prof. López',
  },
];

export const CATEGORIES = ['Todos', 'Nutrición', 'Salud', 'Entrenamiento'] as const;