export const dynamicSubsetIcons = [
  'lucide:arrow-right',
  'lucide:check',
  'lucide:chevron-down',
  'lucide:chevron-left',
  'lucide:chevron-right',
  'lucide:menu',
  'lucide:minus',
  'lucide:plus',
  'lucide:rotate-ccw',
  'lucide:ruler',
  'lucide:search',
  'lucide:shield-check',
  'lucide:star',
  'lucide:x',
  'lucide:stethoscope',
  'lucide:trash-2',
  'lucide:truck',
  'noto:cat',
  'noto:cat-face',
  'noto:dog',
  'noto:dog-face',
  'noto:paw-prints',
  'noto:shopping-cart',
] as const;
